version: '2'

services:
  spark-master:
    image: docker.io/bitnami/spark:SUBST_SPARK_VERSION
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ../../..:/tmp/sparkling-water
      - /tmp/working-dir:/tmp/working-dir
    security_opt:
      - seccomp:unconfined
  spark-worker:
    image: docker.io/bitnami/spark:SUBST_SPARK_VERSION
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=12G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ../../..:/tmp/sparkling-water
      - /tmp/working-dir:/tmp/working-dir
    security_opt:
      - seccomp:unconfined
  h2o:
    image: h2oai/sparkling-water-external-backend:SUBST_SW_VERSION
    volumes:
      - ../../..:/tmp/sparkling-water
      - /tmp/working-dir:/tmp/working-dir
